name: Coreboot build and release.

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: coreboot/coreboot
          ref: main
      - run: find .
      - run: git submodule update --init
