name: Coreboot build and release.

on:
  push:
    paths:
      - 'coreboot/**'
    tags:
      - 'rev*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: coreboot/coreboot-sdk:latest
      options: --privileged
    steps:
      - name: Checkout coreboot repo
        uses: actions/checkout@v6
        with:
          repository: coreboot/coreboot
          ref: main
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: master-this
      - run: find . -maxdepth 1
      - run: git submodule update --init
